### ISSUE TITLE
ASM - Integrate Alert State actions with OIA alerts

### ISSUE THREAD

**Issue by ppenmeth9** [cloudfabrix/api-postman#13]

**Comment by ppenmeth9** [comment]
Currently there are no actions for the Alerts raised by ASM. Instead of providing separate actions such as Clear state, integrate the Alert Actions provided by OIA Alert Actions.

I.e. When the Alert is cleared in OIA (throuhg UI action or through Incident Resolve action), through internal API, the corresponding ASM alert also should be cleared.

This is to provide unified experience when it comes to Alert Management.

We can sync up on this requirement if needed.

**Comment by omprakashpilli** [comment]
Had call with @ppenmeth9 @manojppp @MahendraAkkina and have a design proposal. 

Alert processor need to publish alerts cleared manually/Incident Clear/ITSM ticket clear should be propogated back to ASM. AP will publish cleared alerts to new Topic speicific to ASM so that ASM can read from the topic and clear the respective alert.

@ppenmeth9 please let us know anything is missed as per our discussion.

**Comment by ppenmeth9** [comment]
Requirement and proposed solution is well captured as discussed and i do not have any further comments.

**Comment by Rajulkr** [comment]
Good for 3.5

**Comment by MahendraAkkina** [comment]
Once @omprakashpilli does his part and provide me the information about the kafka topic, I will do my part.

**Comment by omprakashpilli** [comment]
@MahendraAkkina Changes done to publish manually cleared alerts to new kafka topic **clear-alerts-to-asm**.  Please let me know for any issues.

Sample payload published to the topic:
`[{"a_id": "bd1e5ef8-c39a-4915-a820-294273d5e9d5", "project_id": "7d0c10f8-2485-11ef-a99e-0242ac120006", "customer_id": "61b1a5aeedad4852b92ee40a31b3e2c5", "a_alert_category": "Application Performance", "a_asset_type": "infra-account-66", "a_component_name": "Processor", "a_message": "Memory pool \"Processor\" usage [33.86%] exceeded configured value 20.0%", "a_severity": "SEVERE", "a_correlation_status": "CORRELATED", "a_status": "CLEARED", "a_incident_id": "CFX20240705893835ed25", "a_ticket_id": null, "a_rule_name": "Memory", "a_alert_type": "Memory Pool Usage", "a_asset_ip_address": "10.95.133.70", "a_asset_name": "SIM-m0.0-1-250", "a_source_mechanism": "SNMP", "a_source_systemname": "Pulse", "a_event_id": "ea1af750-21ae-458c-8a8f-47ed6df2162f", "a_source_event_id": "1090dcfe-a1ff-46ea-876f-707240d22d2a", "a_rule_id": "aae996c5-6360-460d-98e3-d17da633f80c", "a_burst_rule_name": null, "a_burst_rule_id": null, "a_raised_ts": "2024-07-05T04:44:58.336000", "a_sourceeventreceivedat_ts": "2024-07-05T05:44:58.351000", "a_lastraisereceivedat_ts": "2024-07-05T05:44:58.351000", "a_raisedreceivedat_ts": "2024-07-05T05:44:58.351000", "a_clearreceivedat_ts": "2024-07-05T05:46:33.491000", "a_reviveat_ts": null, "a_created_ts": "2024-07-05T05:45:00.491000", "a_updated_ts": "2024-07-05T05:46:33.511000", "a_cleared_ts": "2024-07-05T05:46:33.491000", "a_repeat_count": 1, "a_cluster_label": null, "a_cluster_score": null, "a_alert_key": "44139090e2c9b11dbc36520a44f50a78", "a_correlation_parent": "9c225d68-3887-43e9-873c-015198e0ef0e", "a_clearcode": null, "a_clear_message": "clear", "a_cause_notes": null, "a_rule_type": "CORRELATE_GROUP", "a_source_system_id": "2a36beb7-7929-45a1-b230-a608b7b88d92", "a_cleared_by": "acme@cfx.com", "a_cluster_id": null, "a_created_by": "OIA", "a_updated_by": "OIA", "a_en_mapper_id": "9bf7c447-5bce-4d23-9865-4ce03f28755b", "a_en_dnsresolvedname": "70.133.95.10.in-addr.arpa. 3460 IN PTR proxypf.engr.cloudfabrix.com.", "a_en_fqdn": "proxypf.engr.cloudfabrix.com", "a_en_matched_datasets": ""}]
rtvc `


@ppenmeth9 We need to define **sourcesystemtype**  as ASM in mapper as a static value so that alert processor can knon an alert is published from ASM. Below is the mapper change to define **sourceSystemType**:
```
{
      "to": "sourceSystemType",
      "func": {
        "evaluate":{
            "expr":"'ASM'"
        }
      }
}
```


Commit link:
https://bitbucket.org/cloudfabrix/cfx-rda-alert-processor/pull-requests/336

**Comment by Rajulkr** [comment]
@MahendraAkkina to proceed with other changes

**Comment by MahendraAkkina** [comment]
PR: https://bitbucket.org/cloudfabrix/cfx-library-modules/pull-requests/1976

**Comment by omprakashpilli** [comment]
@ramaraju-potturi please add above step to put sourceSystemName to ASM release document.

**Comment by MahendraAkkina** [comment]
PR: https://bitbucket.org/cloudfabrix/cfx-library-modules/pull-requests/1976
In the kafka message that ASM consumes via `clear-alerts-to-asm` topic, I expect the following fields to there: 
a_alert_type, a_en_alert_name and a_en_md5. There are originally sent as part of the ASM notification as alert_type, alert_name and md5.

**Comment by ramaraju-potturi** [comment]
verified with daily tag working as designed
